{{- $argo := (index .Values "argo-cd") -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.agent.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.agent.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ .Values.agent.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "harness.labels" (dict "context" . "component" .Values.agent.name "name" .Values.agent.name) | nindent 4 }}
{{- if .Values.agent.service.labels }}
{{- toYaml .Values.agent.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.agent.service.type }}
  ports:
  - name: {{ .Values.agent.service.servicePortHttpName }}
    protocol: TCP
    port: {{ .Values.agent.service.servicePortHttp }}
    targetPort: {{ .Values.agent.containerPorts.server }}
    {{- if eq .Values.agent.service.type "NodePort" }}
    nodePort: {{ .Values.agent.service.nodePortHttp }}
    {{- end }}
  - name: {{ .Values.agent.service.servicePortHttpsName }}
    protocol: TCP
    port: {{ .Values.agent.service.servicePortHttps }}
    targetPort: {{ .Values.agent.containerPorts.server }}
    {{- if eq .Values.agent.service.type "NodePort" }}
    nodePort: {{ .Values.agent.service.nodePortHttps }}
    {{- end }}
    {{- with .Values.agent.service.servicePortHttpsAppProtocol }}
    appProtocol: {{ . }}
    {{- end }}
  selector:
    {{- include "harness.selectorLabels" (dict "context" . "name" .Values.agent.name) | nindent 4 }}
{{- if eq .Values.agent.service.type "LoadBalancer" }}
{{- if .Values.agent.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.agent.service.loadBalancerIP | quote }}
{{- end }}
{{- if .Values.agent.service.externalIPs }}
  externalIPs: {{ .Values.agent.service.externalIPs }}
{{- end }}
{{- if .Values.agent.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.agent.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- end -}}
{{- with .Values.agent.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
{{- end }}
{{- with .Values.agent.service.sessionAffinity }}
  sessionAffinity: {{ . }}
{{- end }}
