{{- if .Values.upgrader.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.agent.name }}-upgrader
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "harness.agentLabels" (dict "context" . "component" .Values.upgrader.name "name" .Values.upgrader.name) | nindent 4 }}
spec:
  schedule: "{{ .Values.upgrader.cron }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.upgrader.startDeadline }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.upgrader.name }}
          containers:
            - name: upgrader
              image: {{ .Values.upgrader.image }}
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 65534
                seccompProfile:
                  type: RuntimeDefault
              envFrom:
                - configMapRef:
                    name: {{ .Values.agent.name }}-upgrader
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
            {{- if .Values.agent.proxy.enabled }}
                - name: PROXY_HOST
                  value: {{ .Values.upgrader.config.proxyHost }}
                - name: PROXY_PORT
                  value: {{ .Values.upgrader.config.proxyPort }}
                - name: PROXY_SCHEME
                  value: {{ .Values.upgrader.config.proxyScheme }}
                - name: PROXY_USER
                  value: {{ .Values.upgrader.config.proxyUser }}
                - name: PROXY_PASSWORD
                  value: {{ .Values.upgrader.config.proxyPassword }}
                - name: NO_PROXY
                  value: localhost,{{ include "argocd.serviceName" (dict "context" . "component" "repo-server" "Values" .Values) | default "argocd-repo-server" }},{{ include "argocd.redisServiceName" . | default "argocd-redis" }},127.0.0.1,$(KUBERNETES_SERVICE_HOST),kubernetes.default.svc,{{ .Values.agent.name | default "gitops-agent" }}
            {{- end }}
                - name: UPGRADER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: GITOPS_AGENT_TOKEN
                      name: gitops-agent
              volumeMounts:
                - name: mtls-certs
                  mountPath: /etc/mtls
                - name: config-volume
                  mountPath: /etc/config
                {{- if .Values.harness.secrets.caData.enabled }}
                - name: certvol
                  mountPath: /ca-bundle/ca.bundle
                  subPath: ca.bundle
                {{- end }}
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.agent.name }}-upgrader
            {{- if .Values.harness.secrets.caData.enabled }}
            - name: certvol
              secret:
                secretName: {{ if .Values.agent.existingSecrets.caBundle }}{{ .Values.agent.existingSecrets.caBundle }}{{ else }}{{ .Values.agent.name }}-ca{{ end }}
                optional: true
                items:
                  - key: ca.bundle
                    path: ca.bundle
            {{- end }}
            - name: mtls-certs
              secret:
                secretName: {{ if .Values.agent.existingSecrets.mtls }}{{ .Values.agent.existingSecrets.mtls }}{{ else }}{{ .Values.agent.name }}-mtls{{ end }}
                optional: true
                items:
                  - key: client.crt
                    path: client.crt
                  - key: client.key
                    path: client.key
          restartPolicy: Never
---
{{- end }}
